import './globals.css'
import type { Metadata } from 'next'
import { Epilogue } from 'next/font/google'

const epilogue = Epilogue({ subsets: ['latin'], weight: ['500', '700'], variable: '--font-epilogue' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${epilogue.variable} font-sans text-lg bg-neutral-white text-neutral-gray `}>{children}</body>
    </html>
  )
}
